### ISSUE TITLE
Bug - wrong encoding

### ISSUE THREAD

**Issue by etwrou** [Stremio/stremio-opensubtitles#8]
Hi

subtitles in Polish language downloaded by this addon are displayed with encoding issues.
They are displayed with characters in 1252 instead of 1250.
Examples:
³ instead of ł
¹ instead of ą
œ instead of ś

Stremio: 4.4.52-1 deb
OS: Ubuntu 18.04

Thanks

**Comment by TRtomasz** [comment]
For which movie does it happen?

**Comment by etwrou** [comment]
@TRtomasz Hi,

**Comment by etwrou** [comment]
@TRtomasz Hi

have you reproduced the issue with the movies I provided?
Let me know if I need to provide anything more.

Thanks

**Comment by TRtomasz** [comment]
I think this error should be fixed now, I'v just checked subtitles for Batman Begins and chars like ł or ć are properly displayed.

**Comment by etwrou** [comment]
> I think this error should be fixed now, I'v just checked subtitles for Batman Begins and chars like ł or ć are properly displayed.

Thanks for checking.
I also have rechecked right now after upgrading Stremio to v4.4.106-1 and unlucky it seems to still exists.
I have tested it on The Godfather (first list from from torrentio addon, 2.4G,1080p), sub it 6462056.
The same for Batman Begins (3rd link from Torrentio addon,1080p, 1.61GB), sub id 3271755.

Could you please check some of them?
I believe the movie file you have checked had luckily well encoded subtitle file so the issue did not appear to you.
 
Thanks

**Comment by TRtomasz** [comment]
![image](https://user-images.githubusercontent.com/40594253/78713869-32b4a980-791b-11ea-9360-6e6e78048b6a.png)
Everything is fine in mentioned godfather subtitles

**Comment by etwrou** [comment]
> image
> Everything is fine in mentioned godfather subtitles

Thanks for this screenshot.

Simple upgrading package and reinstalling addons did not work in this case.

It looks like in order to have it working fine like you have, I had to completely purge Stremio and its .cache and .local in home dir and then install it again. Then it worked.

Thanks Tomasz!
